return {}
-- return {
--   {
--     "willothy/blam.nvim",
--     build = "make",
--     opts = {
--       -- options
--       config = true,
--     },
--     init = function()
--       require("blam").toggle()
--     end,
--   },
-- }
